set(_CATKIN_CURRENT_PACKAGE "vision")
set(vision_MAINTAINER "yeshi <yeshi@todo.todo>")
set(vision_DEPRECATED "")
set(vision_VERSION "0.0.0")
set(vision_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "opencv2" "cv_bridge" "image_transport" "robot_description")
set(vision_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "opencv2" "cv_bridge" "image_transport" "robot_description")
set(vision_BUILDTOOL_DEPENDS "catkin")