set(_CATKIN_CURRENT_PACKAGE "transform")
set(transform_MAINTAINER "yeshi <yeshi@todo.todo>")
set(transform_DEPRECATED "")
set(transform_VERSION "0.0.0")
set(transform_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "tf")
set(transform_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs" "geometry_msgs" "tf")
set(transform_BUILDTOOL_DEPENDS "catkin")